# Generated by Django 2.2.19 on 2022-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='item.Order'),
        ),
    ]
