# Generated by Django 2.2.19 on 2022-11-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20221129_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='order',
            new_name='orders',
        ),
    ]
